services:
  - type: worker
    name: weather-bot
    env: docker
    buildCommand: ./gradlew shadowJar
    startCommand: java -jar /app/bot.jar
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        sync: false
